### ISSUE TITLE
[Development] Unable to start openstates.org on Windows via docker-compose

### ISSUE THREAD

**Issue by rogerscg** [openstates/issues#177] opened 2020-12-05 18:48 UTC
I'm trying to bring up a local instance of openstates.org on my Windows machine. I was able to do this successfully on my Macbook.

The error I'm seeing relates to Django:
`django_1  | standard_init_linux.go:211: exec user process caused "no such file or directory"`

When searching for this error, I see a few solutions that pertain to switching line endings from CRLF to LF. I checked all Dockerfiles and other configs to see if there was a stray file that had CRLF line endings, but couldn't find anything. I also followed the documentation and set the Github config using `git config --global core.autocrlf false`, so I'm not convinced line endings are the issue here.

Any help would be appreciated.

Windows OS Version: Windows 10 Pro 19041.630
Docker Version 19.03.13

**Comment by jamesturk** [comment] 2020-12-07 21:45
If someone that's knowledgeable in Docker & Windows has a chance & sees this, a pointer or two as to what might be going on would be appreciated.

**Comment by cars** [comment] 2021-01-15 06:23
@rogerscg  I'm seeing this same error if I try to clone the repo with  ```core.autolf = true``` beforehand, but with it set to ```false``` it starts up just fine for me.  I'm on Win 10 (version 20H2 (Build 19042.746)) with docker desktop v3.0.4

Did you make sure you deleted the actual images before re-cloning the repo and running compose again?

**Comment by jamesturk** [comment] 2021-01-19 16:23
@cars thanks for confirming this, I had another report from a colleague that they couldn't reproduce this either.  Going to close this one for now, @rogerscg if you have further trouble let me know

**Closed as completed by jamesturk** 2021-01-19 16:23 UTC
Labels: help wanted, component:web
