### ISSUE TITLE
MN small number of actions ignored or mischaracterized

### ISSUE THREAD

**Issue by jessemortenson** [openstates/issues#219] opened 2021-01-04 19:32 UTC
**Issue Description:** MN bill actions can include entries that lack any kind of date. Common example is something like "Chapter number 2" under the House actions. This is probably a very minor bug, since Senate actions usually include a corresponding entry "Secretary of State Chapter 2 12/16/2020" that does include a date. 

That said - is there a way generally in OS to ingest un-dated but sequential bill actions?

Related issue: at least one type of action does include a date in the text of the action, however that date is not the date the action took place:

`Effective date Art. 1-2, 3, Sec. 1, Art. 4-5, 6, Sec. 2, and Art. 7 12/17/21; Art. 3, Sec. 2 06/30/21; Art. 6, Sec. 1 10/01/20 (retroactive)`

In OS `12/17/21` is interpreted as the bill action date, which is not accurate. This results in kinda weird bill actions data for the bill (actions in the future). 

**URL where this issue may be seen (API or OpenStates.org):**
https://openstates.org/mn/bills/2020s7/SF31/

**Source URL of correct data if applicable:**
https://www.revisor.mn.gov/bills/bill.php?b=House&f=SF0031&ssn=7&y=2020

**Comment by showerst** [comment] 2021-01-04 19:46
There's nothing in the data model for this right now, unfortunately. If we had dates before/after we could maybe infer it, but since they're just undated and we don't like to make up data, it's a bit of a rock and hard place.

I think we could argue that chapter number and effective date aren't actually actions taken by the legislature, that's just where MN happens to put them. We have another open bug about the data model for citations. 

In other states we add those as extras keys, but MN is gnarly because effective dates of different sections of a bill can vary, so it doesn't really fit as a nice single ```bill.extras['effective'] = 'Y-m-d'``` either.

In this case the bill action date for that is a bug, but just FYI actions in the future do happen in a few states.

I'd propose that the right thing to do here is to keep skipping them as actions, including removing the wrongly inferred dates, but when those actions are found add extras with the whole effective date string and chapter number. 

Thoughts?

**Comment by jamesturk** [comment] 2021-02-10 22:10
this sounds good to me, @jessemortenson ?

**Comment by jessemortenson** [comment] 2021-02-12 02:36
Yeah, that mostly makes sense. The question that it leaves me with is still regarding ingesting dated bill actions. It seems like in the OS schema the ordering of actions is meaningful: often bills have more than one action on the same date and that order/sequence is meaningful in the domain. For example https://openstates.org/wv/bills/2021/HB2056/ lists the actions on the same day in the same order as the source.

If location in the sequence is meaningful (within a day) then it seems like it could make sense to ingest an action without a date (that nonetheless has a clear location in the sequence of actions). 

I'm fine closing this specific MN issue, or deprioritizing it or whatever. Have you noticed it coming up in other states?

**Comment by showerst** [comment] 2021-02-12 16:23
We sort of have three different issues to be thinking about here --

1. Multiple actions on the same date (no time) where we know the date AND the sequence
2. Multiple actions on the same date (no time) where we know the date but the sequence is undefined
2. Actions with no date at all

Thoughts there --

1. With idempotent scrapes, now multiple actions in sequence on with the same `date[time]` are a matter of controlling the order they get added in the scraper code, and then how they get read into/out of the DB right? That seems more tweakable than trying to enrich the data model with a secondary order key.
2. I don't think we should be ingesting actions without dates, because the definition of an action is "an action (and category) that was taken by a legislature on a bill at a date[time]". A lot of downstream and display code is simplified by this assumption, which is usually true. Without that assumption you can't ask questions like "When was this bill last acted on by $CHAMBER?".
3. Generally something without a date that a state lists in the actions list on their website (usually chapter numbers, effective dates, code cites, etc) should be a different key in our model.

The downside to the 'order is relevant all the way from scraper to display' is we have to make some assumptions in the scraper about how the display order should be. If MN puts new actions on the same day at the top and WY puts them on the bottom, we'd be picking a lane by sorting them all the same. Frankly I prefer that, but can see the argument of matching the state site too.

**Comment by jamesturk** [comment] 2021-02-12 19:02
As for actions without dates, I agree that they don't really fit the model of what an action is.  I can't think of any real actions we've encountered that had this issue, there are however a few cases where we use the prior date when two actions are back to back and the state omits a second date, but I think that's different (and it'd feel like a regression to drop the date from the latter IMO).

Let's push forward on adding the appropriate fields for effective date/etc. though, I'd like to get in the habit of adding these things once consensus is reached whereas in the Open Civic Data days we'd often get stuck with indecision, but we can move a bit faster now.  (See #277, I'm doing some thinking on a more streamlined process to get consensus and improve the model.)

As for the other issues: FWIW, behind the scenes on import the position in the JSON gets saved as a BillAction.order field, and ordering is then done using that field as well as the date.  I currently agree that adding it to the JSON itself isn't needed and probably just leads to complexity that isn't needed.  There is code however that switches the display order on OpenStates.org to make them consistent, see #284 for a place where this seems to be happening.  The good news is that the way we do things we have enough information to fix this, it'll jus

**Comment by showerst** [comment] 2021-02-12 19:28
Cool, i'm going to close this ticket then. I'll pick up on that effective dates / other metadata issue next week, unless someone beats me to it.

RE:data model changes yeah excited for us to put in a proper process. I think the number of stakeholders paying really detailed attention is fairly low (and engaged, heh) so we can move fast, but make it a more open process than an Openstates/Govhawk/CivicEagle just agreeing to something on slack.

**Closed as completed by showerst** 2021-02-12 19:28 UTC
Labels: type:bug
