### ISSUE TITLE
Michigan Bills Created since 3/18 Are Missing Actions + other data

### ISSUE THREAD

**Issue by donaldwasserman** [openstates/issues#363] opened 2021-03-19 10:40 UTC
This is the right template to select if you're reporting an issue with bill or vote data from Open States.

**Issue Description:**
It appears that the Michigan Legislature website possibly updated it's bill information table. I can dig in a bit more this weekend, but wanted to add this issue.

all the the `actions` list is missing plus all the related data on the main `BIll` object.

**URL where this issue may be seen (API or OpenStates.org):**
https://v3.openstates.org/bills/ocd-bill/31ef12d0-3c46-47b1-a574-ee183bd52931
https://openstates.org/mi/bills/2021-2022/HB4532/

**Source URL of correct data if applicable:**
http://legislature.mi.gov/doc.aspx?2021-HB-4532

**Comment by showerst** [comment] 2021-03-19 14:04
Confirmed, we're not seeing scraping here. I'll check this out.

**Comment by showerst** [comment] 2021-03-19 14:11
@donaldwasserman thanks for the report. Looks like they changed date formats on us, I've merged a fix, so the data should update later today. I'll check back this afternoon and close this bug if it's loaded.

**Comment by donaldwasserman** [comment] 2021-03-19 17:30
@showerst Looks like all the data (and by all, i mean the three i checked) is correct.

**Closed as completed** 2021-03-23 15:26 UTC
Labels: type:bug
